/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoTriqui;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author juanp
 */
public class JuegoTriqui extends javax.swing.JFrame {

    /**
     * Creates new form JuegoTriqui
     */    
    
    
    String turno = "O";
    JLabel labels[] = new JLabel[9];
    int contX = 0;
    int contO = 0;
    boolean ganador = false;
    
    public void quitarLinea(){
        jpn1.setVisible(false);
        jpn2.setVisible(false);
        jpn3.setVisible(false);
        jpn4.setVisible(false);
        jpn5.setVisible(false);
        jpn6.setVisible(false);
        lblDiagonal1.setVisible(false);
        lblDiagonal2.setVisible(false);
    }
  
    public JuegoTriqui() {
        initComponents();
       
        setTitle("Triqui");
        setBounds(200,100,814,529);
        ImageIcon imagen2 = new ImageIcon("src/Imagenes/equis.png");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        ImageIcon imagen = new ImageIcon("src/Imagenes/circulo.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        quitarLinea();
        labels[0] = lblCas1;
        labels[1] = lblCas2;
        labels[2] = lblCas3;
        labels[3] = lblCas4;
        labels[4] = lblCas5;
        labels[5] = lblCas6;
        labels[6] = lblCas7;
        labels[7] = lblCas8;
        labels[8] = lblCas9;
        
        txtTurno.setBackground(new java.awt.Color(0,0,0,1));
        txtJugadorO.setBackground(new java.awt.Color(0,0,0,1));
        txtJugadorX.setBackground(new java.awt.Color(0,0,0,1));
        txtPuntaje.setBackground(new java.awt.Color(0,0,0,1));
        lblJgx.setIcon(icono2);
        lblJgO.setIcon(icono);     
        lblTurno.setIcon(icono);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiagonal2 = new javax.swing.JLabel();
        lblDiagonal1 = new javax.swing.JLabel();
        jpn2 = new javax.swing.JPanel();
        jpn3 = new javax.swing.JPanel();
        jpn4 = new javax.swing.JPanel();
        jpn5 = new javax.swing.JPanel();
        jpn6 = new javax.swing.JPanel();
        jpn1 = new javax.swing.JPanel();
        lblCas1 = new javax.swing.JLabel();
        lblCas2 = new javax.swing.JLabel();
        lblCas3 = new javax.swing.JLabel();
        lblCas4 = new javax.swing.JLabel();
        lblCas5 = new javax.swing.JLabel();
        lblCas6 = new javax.swing.JLabel();
        lblCas7 = new javax.swing.JLabel();
        lblCas8 = new javax.swing.JLabel();
        lblCas9 = new javax.swing.JLabel();
        txtPuntajeO = new javax.swing.JTextField();
        txtPuntaje = new javax.swing.JTextField();
        txtPuntajeX = new javax.swing.JTextField();
        txtJugadorO = new javax.swing.JTextField();
        lblJgO = new javax.swing.JLabel();
        lblJgx = new javax.swing.JLabel();
        txtJugadorX = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTurno = new javax.swing.JTextField();
        lblTurno = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiagonal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagonalO2.png"))); // NOI18N
        getContentPane().add(lblDiagonal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 590, 410));

        lblDiagonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagonalO1.png"))); // NOI18N
        getContentPane().add(lblDiagonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, 410));

        jpn2.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jpn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 24, 366));

        jpn3.setBackground(new java.awt.Color(255, 255, 0));
        jpn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jpn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 24, 366));

        jpn4.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jpn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 24, 366));

        jpn5.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jpn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 350, 20));

        jpn6.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jpn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 350, 20));

        jpn1.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jpn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 350, 20));

        lblCas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas1MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 110, 110));

        lblCas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas2MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 110, 110));

        lblCas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas3MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, 110));

        lblCas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas4MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 110, 110));

        lblCas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas5MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 110, 110));

        lblCas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas6MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 110, 110));

        lblCas7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas7MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 110, 110));

        lblCas8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas8MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 110, 110));

        lblCas9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCas9MouseClicked(evt);
            }
        });
        getContentPane().add(lblCas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 110, 110));

        txtPuntajeO.setEditable(false);
        txtPuntajeO.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPuntajeO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntajeO.setText("0");
        getContentPane().add(txtPuntajeO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 40, 30));

        txtPuntaje.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        txtPuntaje.setText("Puntaje");
        txtPuntaje.setBorder(null);
        txtPuntaje.setOpaque(false);
        getContentPane().add(txtPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 81, -1));

        txtPuntajeX.setEditable(false);
        txtPuntajeX.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPuntajeX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntajeX.setText("0");
        getContentPane().add(txtPuntajeX, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 40, 30));

        txtJugadorO.setEditable(false);
        txtJugadorO.setBackground(new java.awt.Color(249, 247, 247));
        txtJugadorO.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtJugadorO.setForeground(new java.awt.Color(255, 255, 255));
        txtJugadorO.setText("Jugador ");
        txtJugadorO.setBorder(null);
        txtJugadorO.setCaretColor(new java.awt.Color(255, 255, 255));
        txtJugadorO.setOpaque(false);
        getContentPane().add(txtJugadorO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        lblJgO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/circulo.png"))); // NOI18N
        getContentPane().add(lblJgO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 110));

        lblJgx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equis.png"))); // NOI18N
        getContentPane().add(lblJgx, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 110, 110));

        txtJugadorX.setEditable(false);
        txtJugadorX.setBackground(new java.awt.Color(255, 255, 255));
        txtJugadorX.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtJugadorX.setForeground(new java.awt.Color(255, 255, 255));
        txtJugadorX.setText("Jugador");
        txtJugadorX.setToolTipText("");
        txtJugadorX.setBorder(null);
        txtJugadorX.setCaretColor(new java.awt.Color(255, 255, 255));
        txtJugadorX.setOpaque(false);
        txtJugadorX.setSelectionEnd(8);
        txtJugadorX.setSelectionStart(8);
        txtJugadorX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugadorXActionPerformed(evt);
            }
        });
        getContentPane().add(txtJugadorX, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 128, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Nuevo juego");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 170, 35));

        txtTurno.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(255, 255, 255));
        txtTurno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTurno.setText("Turno");
        txtTurno.setBorder(null);
        txtTurno.setOpaque(false);
        getContentPane().add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 49));
        getContentPane().add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 110));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Resetear  puntaje");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 190, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoTriqui.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lblCas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas1MouseClicked
        presiona(1);
    }//GEN-LAST:event_lblCas1MouseClicked

    private void lblCas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas2MouseClicked
        presiona(2);
    }//GEN-LAST:event_lblCas2MouseClicked

    private void lblCas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas3MouseClicked
        presiona(3);
    }//GEN-LAST:event_lblCas3MouseClicked

    private void lblCas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas4MouseClicked
        presiona(4);
    }//GEN-LAST:event_lblCas4MouseClicked

    private void lblCas5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas5MouseClicked
        presiona(5);
    }//GEN-LAST:event_lblCas5MouseClicked

    private void lblCas6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas6MouseClicked
        presiona(6);
    }//GEN-LAST:event_lblCas6MouseClicked
    
    private void lblCas7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas7MouseClicked
        presiona(7);
    }//GEN-LAST:event_lblCas7MouseClicked

    private void lblCas8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas8MouseClicked
        presiona(8); 
    }//GEN-LAST:event_lblCas8MouseClicked

    private void lblCas9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCas9MouseClicked
        presiona(9);
    }//GEN-LAST:event_lblCas9MouseClicked

    private void txtJugadorXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugadorXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugadorXActionPerformed
   
    public void presiona(int casilla) {
        ImageIcon imagen = new ImageIcon("src/Imagenes/circulo.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        
            if (labels[casilla-1].getText().equals("")){

                if(turno.equals("O")){
                    labels[casilla-1].setIcon(icono);
                    labels[casilla-1].setText(turno);
                    determinaGanador();
                    if (!ganador){
                        cambiaTurno();
                        if(!bloquearJugada()){
                            tiraMaquina();
                            determinaGanador();
                        }
                    }
                } 
            }   
    }
    
    public void tiraMaquina(){
        ImageIcon imagen2 = new ImageIcon("src/Imagenes/equis.png");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        if(turno.equals("X")){ 
            for (int i = 0; i<labels.length; i++){
                if (labels[i].getText().equals("")) {
                    labels[i].setIcon(icono2);
                    labels[i].setText(turno);
                    cambiaTurno();
                    break;
                } 
            }
        }
    }
    
    
    public boolean bloquearJugada(){
        ImageIcon imagen2 = new ImageIcon("src/Imagenes/equis.png");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        boolean bandera = false;
        if(turno.equals("X")){
            if (labels[0].getText().equals("O") && labels[1].getText().equals("O") && labels[2].getText().equals("")){
                labels[2].setIcon(icono2);
                labels[2].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[0].getText().equals("O") && labels[3].getText().equals("O") && labels[6].getText().equals("")){
                labels[6].setIcon(icono2);
                labels[6].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[3].getText().equals("O") && labels[4].getText().equals("O") && labels[5].getText().equals("")){
                labels[5].setIcon(icono2);
                labels[5].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[6].getText().equals("O") && labels[7].getText().equals("O") && labels[8].getText().equals("")){
                labels[8].setIcon(icono2);
                labels[8].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[1].getText().equals("O") && labels[2].getText().equals("O") && labels[0].getText().equals("")){
                labels[0].setIcon(icono2);
                labels[0].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[4].getText().equals("O") && labels[5].getText().equals("O") && labels[3].getText().equals("")){
                labels[3].setIcon(icono2);
                labels[3].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[7].getText().equals("O") && labels[8].getText().equals("O") && labels[6].getText().equals("")){
                labels[6].setIcon(icono2);
                labels[6].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[1].getText().equals("O") && labels[4].getText().equals("O") && labels[7].getText().equals("")){
                labels[7].setIcon(icono2);
                labels[7].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[2].getText().equals("O") && labels[5].getText().equals("O") && labels[8].getText().equals("")){
                labels[8].setIcon(icono2);
                labels[8].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[8].getText().equals("O") && labels[5].getText().equals("O") && labels[2].getText().equals("")){
                labels[2].setIcon(icono2);
                labels[2].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[7].getText().equals("O") && labels[4].getText().equals("O") && labels[1].getText().equals("")){
                labels[1].setIcon(icono2);
                labels[1].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[6].getText().equals("O") && labels[3].getText().equals("O") && labels[0].getText().equals("")){
                labels[0].setIcon(icono2);
                labels[0].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[0].getText().equals("O") && labels[4].getText().equals("O") && labels[8].getText().equals("")){
                labels[8].setIcon(icono2);
                labels[8].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[8].getText().equals("O") && labels[4].getText().equals("O") && labels[0].getText().equals("")){
                labels[0].setIcon(icono2);
                labels[0].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[2].getText().equals("O") && labels[4].getText().equals("O") && labels[6].getText().equals("")){
                labels[6].setIcon(icono2);
                labels[6].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            } else if (labels[6].getText().equals("O") && labels[4].getText().equals("O") && labels[2].getText().equals("")){
                labels[2].setIcon(icono2);
                labels[2].setText(turno);
                cambiaTurno();
                determinaGanador();
                bandera= true;
                
            }
        }
        return bandera;
    }
    
    public void cambiaTurno(){
        ImageIcon imagen2 = new ImageIcon("src/Imagenes/equis.png");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        ImageIcon imagen = new ImageIcon("src/Imagenes/circulo.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        
        if (turno.equals("X")) {
            turno = "O";
            lblTurno.setIcon(icono);
        } else {
            turno = "X";
            lblTurno.setIcon(icono2);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImageIcon imagen = new ImageIcon("src/Imagenes/circulo.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblCas1.getWidth(),lblCas1.getHeight(),Image.SCALE_DEFAULT));
        
        lblCas1.setIcon(null);
        lblCas1.setText("");
        lblCas2.setIcon(null);
        lblCas2.setText("");
        lblCas3.setIcon(null);
        lblCas3.setText("");
        lblCas4.setIcon(null);
        lblCas4.setText("");
        lblCas5.setIcon(null);
        lblCas5.setText("");
        lblCas6.setIcon(null);
        lblCas6.setText("");
        lblCas7.setIcon(null);
        lblCas7.setText("");
        lblCas8.setIcon(null);
        lblCas8.setText("");
        lblCas9.setIcon(null);
        lblCas9.setText("");              
        quitarLinea();
        turno="O";
        lblTurno.setIcon(icono);
        ganador = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        contO=0;
        txtPuntajeO.setText(Integer.toString(contO));
        contX=0;
        txtPuntajeX.setText(Integer.toString(contX));
    }//GEN-LAST:event_jButton2ActionPerformed

    public void ganaO(){
        contO += 1;
        txtPuntajeO.setText(Integer.toString(contO));
    }
    public void ganaX(){
        contX += 1;
        txtPuntajeX.setText(Integer.toString(contX));
    }
    
    public void determinaGanador(){
        
        if (!ganador){
            if (lblCas1.getText().equals("O")&&lblCas2.getText().equals("O")&&lblCas3.getText().equals("O")){
                jpn5.setVisible(true);
                ganaO();
                ganador = true;

            }else if (lblCas1.getText().equals("O")&&lblCas4.getText().equals("O")&&lblCas7.getText().equals("O")){
                jpn2.setVisible(true);
                ganaO();
                ganador = true;
            }else if (lblCas1.getText().equals("O")&&lblCas5.getText().equals("O")&&lblCas9.getText().equals("O")){
                lblDiagonal1.setVisible(true);
                ganaO();
                ganador = true;
            }else if(lblCas2.getText().equals("O")&&lblCas5.getText().equals("O")&&lblCas8.getText().equals("O")){
                jpn3.setVisible(true);
                ganaO();
                ganador = true;
            }else if (lblCas3.getText().equals("O")&&lblCas6.getText().equals("O")&&lblCas9.getText().equals("O")){
                jpn4.setVisible(true);
                ganaO();
                ganador = true;
            }else if (lblCas3.getText().equals("O")&&lblCas5.getText().equals("O")&&lblCas7.getText().equals("O")){
                lblDiagonal2.setVisible(true);
                ganaO();
                ganador = true;
            }else if (lblCas4.getText().equals("O")&&lblCas5.getText().equals("O")&&lblCas6.getText().equals("O")){
                jpn6.setVisible(true);
                ganaO();
                ganador = true;
            }else if (lblCas7.getText().equals("O")&&lblCas8.getText().equals("O")&&lblCas9.getText().equals("O")){
                jpn1.setVisible(true);
                ganaO();
                ganador = true;
            }else {
                if (lblCas1.getText().equals("X")&&lblCas2.getText().equals("X")&&lblCas3.getText().equals("X")){
                    jpn5.setVisible(true);
                    ganaX();   
                    ganador = true;
                }else if (lblCas1.getText().equals("X")&&lblCas4.getText().equals("X")&&lblCas7.getText().equals("X")){
                    jpn2.setVisible(true);
                    ganaX();
                    ganador = true;
                }else if (lblCas1.getText().equals("X")&&lblCas5.getText().equals("X")&&lblCas9.getText().equals("X")){
                    lblDiagonal1.setVisible(true);
                    ganaX();
                    ganador = true;
                }else if(lblCas2.getText().equals("X")&&lblCas5.getText().equals("X")&&lblCas8.getText().equals("X")){
                    jpn3.setVisible(true);
                    ganaX();
                    ganador = true;
                }else if (lblCas3.getText().equals("X")&&lblCas6.getText().equals("X")&&lblCas9.getText().equals("X")){
                    jpn4.setVisible(true);
                    ganaX();
                    ganador = true;
                }else if (lblCas3.getText().equals("X")&&lblCas5.getText().equals("X")&&lblCas7.getText().equals("X")){
                    lblDiagonal2.setVisible(true);
                    ganaX();
                    ganador = true;
                }else if (lblCas4.getText().equals("X")&&lblCas5.getText().equals("X")&&lblCas6.getText().equals("X")){
                    jpn6.setVisible(true);
                    ganaX();
                    ganador = true;
                }else if (lblCas7.getText().equals("X")&&lblCas8.getText().equals("X")&&lblCas9.getText().equals("X")){
                    jpn1.setVisible(true);
                    ganaX();       
                    ganador = true;
                }
            }
            if(ganador){
                turno="Z";
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoTriqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoTriqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoTriqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoTriqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoTriqui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn3;
    private javax.swing.JPanel jpn4;
    private javax.swing.JPanel jpn5;
    private javax.swing.JPanel jpn6;
    private javax.swing.JLabel lblCas1;
    private javax.swing.JLabel lblCas2;
    private javax.swing.JLabel lblCas3;
    private javax.swing.JLabel lblCas4;
    private javax.swing.JLabel lblCas5;
    private javax.swing.JLabel lblCas6;
    private javax.swing.JLabel lblCas7;
    private javax.swing.JLabel lblCas8;
    private javax.swing.JLabel lblCas9;
    private javax.swing.JLabel lblDiagonal1;
    private javax.swing.JLabel lblDiagonal2;
    private javax.swing.JLabel lblJgO;
    private javax.swing.JLabel lblJgx;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txtJugadorO;
    private javax.swing.JTextField txtJugadorX;
    private javax.swing.JTextField txtPuntaje;
    private javax.swing.JTextField txtPuntajeO;
    private javax.swing.JTextField txtPuntajeX;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
